### ISSUE TITLE
The example for chunk* in the document failed

### ISSUE THREAD

**Issue by lotabout** [lexi-lambda/racket-collections#12]
The example fails in the doc for [chunk*](http://docs.racket-lang.org/collections/collections-api.html?q=collection#%28def._%28%28lib._data%2Fcollection..rkt%29._chunk%2A%29%29)

Tested in racket 6.8.

**Comment by lexi-lambda** [comment]
This is intentional. The example demonstrates how `chunk*` throws an exception where `chunk` would not.

**Comment by lotabout** [comment]
I see. Sorry for not checking the document carefully.
Actually I was skimming over all the available APIs.

Anyway, thanks!
