### ISSUE TITLE
Generic apply doesn’t properly warn about mutability in contract violations

### ISSUE THREAD

**Issue by lexi-lambda** [lexi-lambda/racket-collections#5]
This should error with the usual `sequence?*` contract warning about mutability.

``` racket
(apply + (vector 1 2 3))
```

```
apply: contract violation
  expected: sequence?
  given: #<procedure:+>
  argument position: 1st
  other arguments...:
   '#(1 2 3)
```

**Comment by AlexKnauth** [comment]
I remember you did this (https://github.com/lexi-lambda/racket-collections/commit/827d298295db9563a0fd0e8886ff1834c3018e38#diff-c5acbcd895166ef38f12c69d2d462717R201) specifically for error messages like this. However it only does that when it's used as a contract, not as a direct predicate. So is there a way to somehow express this in a contract on `apply` ?
